### PR TITLE
Upgrade dependencies for terraform 0.12

### PR DESCRIPTION
**Pull request by hamstah**
Hey sorry I closed the other PR by mistake re-pushing the branch on my fork.

### CODE REVIEW

**Comment by hamstah** [comment]
Hi, 
Any update on merging this? 
Thanks

**Comment by frankreno** [comment]
@hamstah - thanks much for the PR, i would like to spend some more time on this one.  Will try to get reviewed by EOW.

**Comment by hamstah** [comment]
@frankreno cool let me know if I can help. FYI I've been using it since the first PR with no issue for collectors and polling source so these seem to be stable at least.

**Comment by frankreno** [comment]
@hamstah thanks much for the PR, this is great. LGTM. I'll get a new major release with this.

**Comment by hamstah** [comment]
Awesome thanks !

**Comment by heldersepu** [comment]
Anyone successfully running the `TestAccSumologicPollingSource` ?
https://github.com/SumoLogic/sumologic-terraform-provider/blob/7baa465f89bc059ad79ea9e08af271929c5bcaab/sumologic/resource_sumologic_polling_source_test.go#L9
after this change we get: 
```
--- FAIL: TestAccSumologicPollingSource (0.01s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:
        
        - Unassigned variable: The input variable "aws_accesskey" has not been assigned a value. This is a bug in Terraform; please report it in a GitHub issue.
        - Unassigned variable: The input variable "aws_accessid" has not been assigned a value. This is a bug in Terraform; please report it in a GitHub issue.
```

**Comment by bendrucker** [comment]
According to the following, Terraform never intended to support inheriting `TF_VAR_*` in provider tests:

https://github.com/hashicorp/terraform/issues/21162

Tests should use/assert explicitly provided mock data. I'd like to get this repo to a point where the tests run offline and calling out to real resources is opt-in, with clear instructions for how to configure/authenticate those integration tests. Most likely I'd want to use `AWS_{ACCESS_KEY_ID,SECRET_ACCESS_KEY}` and avoid any `TF_VAR_*`.

**Comment by heldersepu** [comment]
> According to the following, Terraform never intended to support inheriting `TF_VAR_*` in provider tests

Thanks for the link @bendrucker ... that really sucks! hopefully, enough people will complain about this "regression" and they will add it

**Comment by bendrucker** [comment]
I agree with Martin's rationale presented there. I think it's an anti-pattern to use `variable {}` blocks in provider acceptance tests. It may more closely resemble user code but the intent is to integration test a specific `resource {}` invocation in isolation. I would similarly not use interpolation for any params.

I'll make a todo to implement the suggestion I posted above and substitute the env vars directly into the config.

**Pull request merged**
