### PR TITLE
Fixes token bug in cloudsyslog_source resource

### PR DESCRIPTION
**Pull request by samrees**
For terraform 12 go.mod was introduced, strangely requiring this module
at an older version and a different path. I think this caused older code to build,
which caused the `token` output to be blank on a sumologic_cloudsyslog_source
resource.

By removing the odd go.mod require line, and making the import in main match the
module name in go.mod (case sensitive), everything seems to build and work as expected.

Also commits go.sum as good practice.

### CODE REVIEW

**Comment by sh-srees** [comment]
Ahhh I am real confused by some recent commits to master:

https://github.com/SumoLogic/sumologic-terraform-provider/commit/4f3c5358eaa154072f7572aae99aca91c88ff05b#diff-37aff102a57d3d7b797f152915a6dc16R1

meanwhile:

https://github.com/SumoLogic/sumologic-terraform-provider/commit/af71c7636dfb31ab4b1e379f95f9afca69976628#diff-7ddfb3e035b42cd70649cc33393fe32cR5

**Comment by frankreno** [comment]
@samrees sorry for the delay.  Odd.  Let me see what happened there.

**Comment by mccartney** [comment]
It might have been me who introduced the wrong line for Github URL. Sorry for that, not intended. Thanks for fixing.

**Comment by samrees** [comment]
Thanks!

**Pull request merged**
