### PR TITLE
addressing some of the results of tfproviderlint and updating packages

### PR DESCRIPTION
**Pull request by seansain**
Ran `tfproviderlint ./...`

Addressed a lot of the issues related to generated code and some of the handwritten providers. Collector issues are still remaining.

Updated packages as well.

Will add a github action to lint the code along with running the acc tests.

### CODE REVIEW

**Comment by sumovishal** [comment]
How do we integrate tfproviderlint in provider build pipeline? Can we make it a prerequisite for every PR?

**Comment by sumovishal** [comment]
This change is too big to review. I am relying on acc tests to surface any issues.  Please make sure you run acc test before merging.

**Comment by seansain** [comment]
@sumovishal  So we can add a github action with the linter to run the linter. However, I do not want to add it until collector team fixes the issues on their side otherwise it will keep addressing same issues.

`continuous-integration/travis-ci/push` runs the acceptance tests.

**Comment by seansain** [comment]
And to review, you can ignore any files in the `vendor` directory. Those are just version changes.

**Pull request merged**
