### PR TITLE
fix schema issues raised by tfproviderlint

### PR DESCRIPTION
**Pull request by bendrucker**
Recently came across [tfproviderlint](https://github.com/bflad/tfproviderlint) and tried it on this provider. The output is:

```
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_cloudsyslog_source_test.go:11:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_collector_test.go:183:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_http_source_test.go:11:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_http_source_test.go:27:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_ingest_budget_test.go:10:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_ingest_budget_test.go:29:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_ingest_budget_test.go:28:6: AT002: acceptance test function name should not include import
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/data_source_sumologic_collector_test.go:9:6: AT003: acceptance test function name should include underscore
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_cloudsyslog_source_test.go:10:6: AT003: acceptance test function name should include underscore
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_collector_test.go:12:6: AT003: acceptance test function name should include underscore
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_collector_test.go:41:6: AT003: acceptance test function name should include underscore
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_collector_test.go:127:6: AT003: acceptance test function name should include underscore
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_collector_test.go:168:6: AT003: acceptance test function name should include underscore
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_http_source_test.go:10:6: AT003: acceptance test function name should include underscore
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_http_source_test.go:26:6: AT003: acceptance test function name should include underscore
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_collector.go:16:3: R003: resource should not include Exists function
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/sumologic_sources.go:274:32: R004: ResourceData.Set() incompatible value type: []github.com/SumoLogic/sumologic-terraform-provider/sumologic.DefaultDateFormat
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/sumologic_sources.go:275:19: R004: ResourceData.Set() incompatible value type: []github.com/SumoLogic/sumologic-terraform-provider/sumologic.Filter
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/data_source_sumologic_collector.go:34:14: S006: schema of TypeMap should include Elem
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_collector.go:45:14: S006: schema of TypeMap should include Elem
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/sumologic_sources.go:167:14: S006: schema of TypeMap should include Elem
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_polling_source.go:35:13: S019: schema should omit Computed, Optional, or Required set to false
```

I went ahead and fixed the two easy issues, namely:

* Maps missing specifications for the type of their elements (string)
* An unnecessary inclusion of `Required: false`

The former actually helps tighten the schema whereas the latter is just cleanup.

The other errors seem low importance or a bit more involved. If you're interested in running tfproviderlint via Travis I'd be happy to tackle the remaining errors.

### CODE REVIEW

**Comment by bendrucker** [comment]
Ha, didn't see #112, looks like you guys are already interested in this!

**Comment by bendrucker** [comment]
@seansain Any interest in this?

**Comment by seansain** [comment]
@bendrucker Thank you for contributing to the repo! I will looking into the terraform side a bit more and will then merge this. Thank you!

**Comment by bendrucker** [comment]
Hey, just checking whether you're still interested in this

**Comment by seansain** [comment]
yes, just verified the changes locally. Thanks for doing this!

**Pull request merged**
