### PR TITLE
Role API support

### PR DESCRIPTION
**Pull request by mtanda**
Fix part of https://github.com/SumoLogic/sumologic-terraform-provider/issues/41 .

Our org use SAML, so I don't need User API support. So, just adding Role API support.

### CODE REVIEW

**Comment by mtanda** [comment]
@frankreno Would you review this PR?
If I need to add test more, please let me know.

**Comment by mtanda** [comment]
@frankreno sorry again, if you are online, please check :-)

**Comment by frankreno** [comment]
@mtanda thanks for the PR! I will be reviewing this later this week.

**Comment by mtanda** [comment]
I found some bugs when adding tests. Update code, ready to review.

**Comment by mtanda** [comment]
@frankreno If you have time, I'd really appreciate it if you check this.

**Comment by frankreno** [comment]
LGTM

**Comment by frankreno** [comment]
@mtanda : I'm going to try to get #40 merged this week and will cut a new release then...

**Comment by mtanda** [comment]
@frankreno Thanks a lot for taking your time!

**Comment by heldersepu** [comment]
Looks like the role api does not like duplicate role names but all we get is:
`Status code 400 - `

But collectors we get a more descriptive message: 
`Status code 400 - A resource with the same name already exists.`

**Pull request merged**
